### ISSUE TITLE
Combining amdgpu with amdgpu-pro

### ISSUE THREAD

**Issue by drahnr** [Mystro256/amdgpu-pro-rpm#2]
I am bit confused, I tried to understand how amdgpu and amdgpu-pro work together based on 2 year old slides http://www.phoronix.com/scan.php?page=news_item&px=MTgwODA

But it is not entirely clear if `amdgpu-pro` (in my case OpenCL) mixes well with the `amdgpu` (in this case the stuff from your copr repo)

Do you have any idea if this will work or not?

I tried to install all of the `amdgpu-pro` ontop of the `amdgpu` but that booted fine until gdm kicked and all I get is a curser and flickering console.

Afaik those two should not exclude each other (I don't think so) or are there kernel patches in your repo that prevent the pro to work properly (ABI fun)?

**Comment by Mystro256** [comment]
Oh ok, so basically I should probably put a warning in the documentation. I will get to that today. So let me preface this with **I have yet to get this working, it always crashes Xorg, please let me know if you figure out how to get this working, else wise don't expect anything out of this yet.**

So basically _amdgpu_ is just a kernel module (i.e. driver) for the newer AMD cards; they are currently working towards having all the GCN cards supported. The kernel from my copr repo (amd-staging-kernel) is just pulled from their staging repo (i.e. the _amgpu_ stuff they are testing before they merge it into the mainline kernel, such as the DAL code).

AMDGPU-PRO, on the other hand, is just a modified version of fglrx/catalyst to work on top of _amdgpu_. The _amdgpu_ module is made to work with both with the open source stack the closed source stack.

This github is trying to get the Ubuntu AMDGPU-PRO driver working with Fedora (amdgpu is already in f24's kernel), but alas, I think we may have to wait for either a Redhat based driver or a generic Linux driver, as it's not playing nicely with Xorg.

**Comment by Mystro256** [comment]
You should take a look at this if you just want the opencl part of AMDGPU-PRO:

http://www.gearsongallium.com/?p=2960

I can try making a package spec if you're interested.

**Comment by drahnr** [comment]
I am very interested in that! That is exactly what I need! (I find it a bit hacky to just change the loader name by sed from `amdgpu` to `amgpo`, but if it is wrapped in a nice package, why not :) )

Let me know if I can be of any help beyond testing the results in the process of creating that package!

**Comment by Mystro256** [comment]
Done, take a look:

https://github.com/Mystro256/amdgpu-pro-opencl-rpm

I don't use openCL, so note that this is majorly untested (i.e. the only thing I've done is run clinfo to see if it picks up on the libraries). Please read the README and please make any issues over there if there is an issue.
